/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_WASMI_C_API_PACKAGE__
#define __RUST_WASMI_C_API_PACKAGE__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {

    uint8_t * ptr;

    size_t len;

    size_t cap;

} Vec_uint8_t;

Vec_uint8_t execute_wasm_binary_to_json (
    uint8_t * wasm_binary,
    size_t wasm_binary_length);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_WASMI_C_API_PACKAGE__ */
