/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_WASMI_C_API_CRATE__
#define __RUST_WASMI_C_API_CRATE__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {

    uint8_t * ptr;

    size_t len;

    size_t cap;

} Vec_uint8_t;

Vec_uint8_t execute_wasm_binary_to_json (
    uint8_t * wasm_binary,
    size_t wasm_binary_length);

int32_t create_wasm_engine (void);

void set_wasm_binary (
    int32_t engine_id,
    uint8_t * wasm_binary,
    size_t wasm_binary_length);

Vec_uint8_t compute_trace (
    int32_t engine_id);

Vec_uint8_t memory_data (
    int32_t engine_id);

void trace_memory_change (
    int32_t engine_id,
    uint32_t offset,
    uint32_t len,
    uint8_t * data,
    size_t data_length);

void register_cb_on_after_item_added_to_logs (
    int32_t engine_id,
    void (*cb)(int32_t, int8_t const *, size_t));


#include <stdbool.h>

bool register_host_fn_i32 (
    int32_t engine_id,
    int8_t const * host_fn_name_ptr,
    int32_t (*host_fn)(int32_t, int8_t const *, size_t, int32_t *, size_t),
    int32_t func_params_count);

bool register_host_fn_i64 (
    int32_t engine_id,
    int8_t const * host_fn_name_ptr,
    int32_t (*host_fn)(int32_t, int8_t const *, size_t, int64_t *, size_t),
    int32_t func_params_count);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_WASMI_C_API_CRATE__ */
