[package]
name = "spec"
version = "0.1.0"
edition = "2021"

[dependencies]
wazm-arena = { path = "../arena" }
wazm-compiler = { path = "../compiler" }
wazm-core = { path = "../core" }
wazm-wasmi = { path = "../runtime" }
byteorder = "1.4.3"
wat = "1.0.66"
anyhow = "1.0.71"
wast = "61.0.0"
